language: ruby
rvm:
  - "2.1.0"
  # - "1.9.3"
  # - "1.9.2"
  # - "1.8.7"
  # - jruby-18mode # JRuby in 1.8 mode
  # - jruby-19mode # JRuby in 1.9 mode
env:
#  - DB=sqlite
#  - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
#  - bundle # exec rspec spec/
  - bundle exec rake
before_script:
#  - mysql -e 'create database my_app_test'
 - psql -c 'create database blogfolio_test' -U jn
bundler_args: --binstubs=./bundler_stubs

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
