development:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.env %>
  pool: 5
  username: jn
  min_messages: ERROR

test:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.env %>
  pool: 5
  username: jn
  min_messages: ERROR

production:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.env %>
  pool: 5
  username: jn
  min_messages: ERROR
