# Local
development:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.env %>
  pool: 5
  username:
  min_messages: ERROR

test:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.env %>
  pool: 5
  username:
  min_messages: ERROR

production:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.env %>
  pool: 5
  username:
  min_messages: ERROR

# Uncomment to upload to Travis
# development:
#   adapter: postgresql
#   encoding: unicode
#   database: blogfolio_<%= Rails.env %>
#   pool: 5
#   username: postgres
#   min_messages: ERROR

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: blogfolio_<%= Rails.env %>
#   pool: 5
#   username: postgres
#   min_messages: ERROR

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: blogfolio_<%= Rails.env %>
#   pool: 5
#   username: postgres
#   min_messages: ERROR
